### ISSUE TITLE
AUR package fails to build do to tre-sitter Gemini and lean

### ISSUE THREAD

**Issue by sweetbbak** [omentic/helix-ext#43]
### Summary

Aur package fails to build:
```
  Failure 1/2: gemini Git command failed.
  Stdout: 
  Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403

  Failure 2/2: lean Git command failed.
  Stdout: 
  Stderr: fatal: unable to access 'https://github.com/Julian/tree-sitter-lean/': Could not resolve host: github.com

  --- stderr
  thread 'main' panicked at 'Failed to fetch tree-sitter grammars: 2 grammars failed to fetch', helix-term/build.rs:5:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think even mainline Helix has an issue with this when updating grammers.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

23.10

**Comment by omentic** [comment]
`Could not resolve host: github.com` is on your end, I believe, but the `https://git.sr.ht/~sfr/tree-sitter-gemini/` is on me, thanks. I merged in a rename the other day but forgot to update the AUR package.

**Comment by omentic** [comment]
Package should be updated now.

**Comment by sweetbbak** [comment]
Thank you! Its a really cool fork. I like the file tree a lot. I haven't seen what other patches there are yet but even just the file tree is really helpful

**Comment by omentic** [comment]
It's cool! I wish it was merged in rather than left out to dry. There were concerns about O(n^2) performance, but this isn't an issue outside of folders like `nix-store`, and the underlying data structure could always be switched out later... Frankly, I don't think the WASM plugin runtime upstream would prefer it to be shipped is going to come in the next half decade, too. (I'll gladly eat my words if proven wrong on this one.)

There is a problem with the added `initial-mode` setting and the file tree, unfortunately. I think I patched out a problematic call but didn't fix the underlying issue - it shouldn't panic, though.

**Comment by sweetbbak** [comment]
lmao I know right, its probably going to be a while. Theres quite a few things that would really improve Helix and I think most people kind of expect a file explorer but the maintainers definitely have a long process and a high standard for what gets merged and when.. but its nice to have it for now even if its not quite perfect yet at least until we get a plugin system of some kind.
